import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Navbar from "@/components/navbar";
import HoverDevCards from "@/components/dock";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Navbar />
        {children}
        {/* <div style={{ position: 'fixed', bottom: 0, width: '100%', zIndex: 1000 }} className="pr-80 pl-80">
          <HoverDevCards/>
        </div> */}
      </body>
    </html>
  );
}
